version: "3.7"

services:
  app:
    image: learning-docker/docker-node:v2
    # mapping port từ hệ điều hành gốc vào port trong container
    ports:
      - "3001:3000"
    # khởi động lại trừ khi bị dừng
    restart: unless-stopped 